### ISSUE TITLE
Upgrade from 16.12.0-4352 to  17.1.0-4511 is failing.

### ISSUE THREAD

**Issue by vivekdubey** [gocd/www.go.cd#413]
We tried to upgrade go-server on amazon linux from 16.12.0-4352 to 17.1.0 and go-server process doesn't start. 
We get following exception:
```
2017-01-18 23:52:27,811  WARN [76@MessageListener for ScheduleCheckListener] JMSMessageListenerAdapter:72 - Error receiving message. Message receiving will continue despite this error.
javax.jms.JMSException: Peer (vm://go-server#1) disposed.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:62)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1267)
	at org.apache.activemq.ActiveMQConnection.asyncSendPacket(ActiveMQConnection.java:1259)
	at org.apache.activemq.ActiveMQSession.asyncSendPacket(ActiveMQSession.java:1863)
	at org.apache.activemq.ActiveMQMessageConsumer.sendPullCommand(ActiveMQMessageConsumer.java:805)
	at org.apache.activemq.ActiveMQMessageConsumer.receive(ActiveMQMessageConsumer.java:503)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:62)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: Peer (vm://go-server#1) disposed.
	at org.apache.activemq.transport.vm.VMTransport.oneway(VMTransport.java:89)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:40)
	at org.apache.activemq.transport.ResponseCorrelator.oneway(ResponseCorrelator.java:60)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1265)
	... 7 more
```

Details of go-server instance:
```
**java** : java version "1.7.0_121"
         OpenJDK Runtime Environment (amzn-2.6.8.1.69.amzn1-x86_64 u121-b00)
         OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)

**OS details** : 4.4.41-35.53.amzn1.x86_64 #1 SMP Mon Jan 9 23:00:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

We had to rollback to previous version to get things working again.

**Comment by ketan** [comment]
This is the repository to raise issues against the website. 17.1 dropped support for Java 7. You need to install Java 8 on the server and agents before you attempt an upgrade.

**Comment by vivekdubey** [comment]
Thanks @ketan.
